version: '3' 
services:
  # wso2-apim:
  #   build: ./wso2-apim
  #   healthcheck:
  #     test: ["CMD", "nc", "-z","localhost", "9443"]
  #     interval: 10s
  #     start_period: 180s
  #     retries: 20
  #   # volumes:
  #   #   - C:\Users\Manie\development\projects\gg\persistent_Data\wso2am:/home/wso2carbon/wso2am-4.1.0/repository/deployment/server/
  #   ports:
  #     - "9443:9443"
  #     - "8280:8280"
  #     - "8243:8243"   

  wso2-is:
    build: ./wso2-is
    ports:
      - "9763:9763"
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 120s
      start_period: 100s